### ISSUE TITLE
Make softwaresaved.github.io a redirect to software.ac.uk

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/softwaresaved.github.io#1]

**Comment by steve-crouch** [comment]
@selina Is this something we'd still like and would make sense? The softwaresaved.github.io page has a link to our website already, but it's not a redirect.

**Comment by selina-aragon** [comment]
@steve-crouch Is this page a sort of home page for our repositories on Github? I'm unsure whether anyone ever lands on it. If it's an easy fix, then perhaps it makes sense to redirect. Otherwise, I'd leave it as is. It already has the information for people to go to our website or our Github page.

**Comment by steve-crouch** [comment]
Yes, essentially you *can* have an organisational homepage on GitHub, but as you say, I doubt anyone really lands on it. I'll leave it as is for now, we can always change it later. Closing.
